---
- name: Deploy AWP Hypervisor
  hosts: hypervisors
  remote_user: root
  gather_facts: no
  tasks:
    - name: Ensure the awp_hypervisor directory exists
      file:
        path: "{{ dst_dir }}"
        state: directory
        mode: '0755'

    - name: Stop any running awp_hypervisor processes
      command: pkill -f awp_hypervisor
      ignore_errors: yes

    - name: Sync hypervisor files (excluding target directory)
      synchronize:
        src: "{{ src_dir }}"
        dest: "{{ dst_dir }}"
        rsync_opts:
          - "--exclude=target"

    - name: Start AWP Hypervisor in tmux
      command:
        cmd: tmux new-session -A -d -s cargo_session 'cargo run --package awp_hypervisor --bin awp_hypervisor'
        chdir: "{{ dst_dir }}"
